### ISSUE TITLE
Add DFS data feed

### ISSUE THREAD

**Issue by bradbarkhouse** [bradbarkhouse/mysportsfeeds-api#1]
Add a new data feed for v1.0 of the API.  Will contain historical daily salaries.

**Comment by bradbarkhouse** [comment]
The feed itself has been created, however we're still massaging and filling in missing information (players and related games) for each entry.

You'll get DraftKings and FanDuel salaries AND actual fantasy points on a daily basis for each player.

As well, we've only been able to go back 2-3 years for all leagues so far.  But that should hopefully be a sufficient starting point for many.

**Comment by znmeb** [comment]
2 - 3 years is more than I have now - basically 2 years of MLB and NBA ;-)

**Comment by bradbarkhouse** [comment]
Woot!  New DFS feed has been announced and is updated early each day for leagues that are in-season, with salaries.  Points are then updated as games are completed, or whenever stats are adjusted.
