### ISSUE TITLE
Change date and time to use ISO 8601 standard

### ISSUE THREAD

**Issue by TheHandsomeCoder** [bradbarkhouse/mysportsfeeds-api#18]
Currently when you access the daily schedule you receive an array of `gameEntry` objects

``` javascript
{
	id: "33462",
	date: "2017-02-14",
	time: "7:00PM",
	awayTeam: {
		ID: "22",
		City: "Colorado",
		Name: "Avalanche",
		Abbreviation: "COL"
	},
	homeTeam: {
		ID: "7",
		City: "New Jersey",
		Name: "Devils",
		Abbreviation: "NJD"
	},
	location: "Prudential Center"
}
```

Rather than having a date and time property would it be possible to add an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date and a timezone property instead. This would allow for easier tracking of when and where games are going to start and make it easier to parse the dates for use with the `play-by-play` endpoint

**Comment by bradbarkhouse** [comment]
Yes absolutely, thanks for adding this, it's been requested by other subscribers as well.

Our API docs mentions using the ET timezone as the default, but we acknowledge that using an ISO compliant timestamp would be far more ideal.

We'll be adding this and other requests into v1.1 of the data feeds, possibly sometime later in the year.

**Comment by bradbarkhouse** [comment]
Done!
