### ISSUE TITLE
DFS Feed: add IDs for DraftKings and FanDuel

### ISSUE THREAD

**Issue by bradbarkhouse** [bradbarkhouse/mysportsfeeds-api#24]
Although we track the source IDs for DraftKings and FanDuel, they're not yet included in the feed.  But they soon will be!

**Comment by znmeb** [comment]
Will that work for historical data? Do you by any chance have the "draft group" data too?

**Comment by bradbarkhouse** [comment]
It may not in every case @znmeb, at least not until we fill in with current IDs.  We'll do that as part of this feature.  As for draft groups, that's not likely as they tend to be ignored right now when we enter them.

**Comment by bradbarkhouse** [comment]
Changes have been pushed to the server to include a **dfsSourceId** for each player, which corresponds to either DraftKings or FanDuel.  Note that we're still retroactively filling in values for some of the historic data, so it may not always be present.

I'll update again when the updates historic back-filling has been completed.

**Comment by bradbarkhouse** [comment]
It looks like we're not able to back-fill every historical DraftKings or FanDuel source ID.  The only way to discover the ID is if they happen to play again in future games, at which point we'll make the updates retroactively for the same player.

And as you pointed out @znmeb, the source ID is dependent on the "slate".  The good news is that we currently record the player ID regardless of the slate and they're matched with a unique player in our system.  If you really need to know the slate, we can add that as a future enhancement.  So right now, a given player could have several source IDs (usually limited to 2 or 3), which you'll need to anticipate and handle.
