### ISSUE TITLE
Introduce API keys

### ISSUE THREAD

**Issue by bradbarkhouse** [bradbarkhouse/mysportsfeeds-api#28]
Currently all API requests use HTTP Basic over SSL with your MySportsFeeds account credentials.  Instead, we'll be switching to use an API key, which is more typical of most APIs and has some other benefits.

Version 1.0 of the API will continue to use HTTP Basic, and will eventually be deprecated and phased out.

**Comment by jason1813** [comment]
soooooooooooooooooooooo. did it ever happen?

**Comment by bradbarkhouse** [comment]
@BUInvent this will be worked on as part of the upcoming v2.0 release, effort to start soon.   We just released v1.2 which will be the last v1.x version.

**Comment by jason1813** [comment]
ok. Thank you.

**Comment by bradbarkhouse** [comment]
Done!
