### ISSUE TITLE
Fix GB in MLB Division Team Standings

### ISSUE THREAD

**Issue by mkove** [bradbarkhouse/mysportsfeeds-api#32]
Currently, all GB (Games Behind) for all Teams are equal to 0.0 for division team standings.  They should reflect the actual games behind the leader in each division.

**Comment by bradbarkhouse** [comment]
Starting work on this now (finally) ...

**Comment by bradbarkhouse** [comment]
Fixed!  All of the *_team_standings feeds will now include the calculated GB stat.
