### ISSUE TITLE
Add players on ice to the play-by-play feed

### ISSUE THREAD

**Issue by edtjbre** [bradbarkhouse/mysportsfeeds-api#34]
I would like to see the addition of all players currently on the ice for every entry in the NHL play-by-play feed.
Entering an issue here after having discussed this with Brad over e-mail.

**Comment by bradbarkhouse** [comment]
Yep, already have that data so won't be a problem to add that.  Although this will have to wait until v1.1 to prevent breaking dependent code from other subscribers.

**Comment by bradbarkhouse** [comment]
We're actually going to have to remodel some things for our hockey coverage in order to do this for every play, and not just goals.

That priority may be pushed to the top soon since our hockey-related code is older and needs to be refactored similar to other sports.

**Comment by bradbarkhouse** [comment]
Done!
