### ISSUE TITLE
Add Vegas Odds

### ISSUE THREAD

**Issue by ty-fleming** [bradbarkhouse/mysportsfeeds-api#35]
I think it would be great to have a Vegas Odds for NFL, MLB, NBA and NHL.

**Comment by bradbarkhouse** [comment]
Although we don't yet have coverage for actual Vegas odds, we do now offer a set of Odds feeds for games, futures, and props.  Current coverage includes: Bovada, 888Sports and BetOnline, with many more to be added in the coming months.
