### ISSUE TITLE
Add Handedness 

### ISSUE THREAD

**Issue by ty-fleming** [bradbarkhouse/mysportsfeeds-api#36]
I could see it being helpful. Especially for MLB if Handedness was an included JSON property.

**Comment by bradbarkhouse** [comment]
Yep, but it definitely applies to other sports as well.

**Comment by jolaurin** [comment]
NHL too, please!

**Comment by bradbarkhouse** [comment]
Work for this, along with draft and contract status, is finally underway!

**Comment by bradbarkhouse** [comment]
All code-relate effort for this has been completed - now it's just about the data entry!
