### ISSUE TITLE
Add Batting Order to Starting Lineup Feed For MLB

### ISSUE THREAD

**Issue by ty-fleming** [bradbarkhouse/mysportsfeeds-api#37]

**Comment by dpekar** [comment]
Lineup order (especially in advance of game starting, like the morning of) would be very useful for us!

Would also really love starting pitchers in this info.

**Comment by bradbarkhouse** [comment]
Actually @dpekar , starting pitchers are already available via the game_startinglineup feed for each game.  Expected as well as actual.

In fact, the batting order will likely just be added to that existing feed for MLB.

**Comment by dpekar** [comment]
Oh awesome @bradbarkhouse , I didn't realize starting pitchers had made it in :)

**Comment by bradbarkhouse** [comment]
Done!  Batting orders are listed as additional positions "BO1" through "BO9".
