### ISSUE TITLE
Add DFS Data to Player Game Logs and Cumulative Stats Feeds

### ISSUE THREAD

**Issue by ty-fleming** [bradbarkhouse/mysportsfeeds-api#38]
This would be helpful for people if there are trying to get an average of how many fantasy points a player has scored over a season or a certain period of time. Instead of have to call the Daily DFS API multiple times.

Include salary and actual scored dfs points. For the cumulative stats fantasy point floor and fantasy point ceiling could be added.

**Comment by bradbarkhouse** [comment]
I think we'll revisit this once we amend our DFS data collection UIs.  But I think I'd prefer if the DFS data were in a feed of it's own, separate of actual stats.  Otherwise the feeds get "heavy" and slower to generate.  Should be pretty easy to join in your client or wrapper code.

**Comment by bradbarkhouse** [comment]
We've now revised part of our non-commercial donation model to restrict access to DFS.  So merging it with other data will be difficult at best.  Instead, it should be possible to perform the merge programmatically elsewhere.

Closing this issue.
