### ISSUE TITLE
Projected DFS Points included in DFS Daily Feed

### ISSUE THREAD

**Issue by ty-fleming** [bradbarkhouse/mysportsfeeds-api#41]
This would require some math...

**Comment by znmeb** [comment]
Are there actually projections in the DFS feed or the schedule feed? I know the DraftKings Android app displays projections for NBA contests, but I haven't been able to find them on the web version or "reverse engineer" the Android app to see where they're coming from.

If you want to "do it with math" there are dozens of algorithms, depending on what inputs you have available. I have some examples in the works at https://github.com/znmeb/Mastering-DFS-Analytics but they're very primitive and really only give usable results for NBA at the moment.

IMHO you're better off subscribing to a projection site; sadly, there's no "consumer reports" that evaluates projection sites for accuracy but *that* math is straightforward, and there are well-known constraints on how good any projection can be.

**Comment by bradbarkhouse** [comment]
While we're planning on adding projections for DFS and "actual" stats, they'll be available in a separate feed.  That makes their generation and maintenance more feasible and timely.
