### ISSUE TITLE
date-range parameter format

### ISSUE THREAD

**Issue by dweitz43** [bradbarkhouse/mysportsfeeds-api#44]
trying something like 
```
https://api.mysportsfeeds.com/v1.1/pull/nhl/2016-2017-regular/player_gamelogs.json?player=jamie-benn&date=from-20161013-to-20161022
```

returns 404, but something like 
```
https://api.mysportsfeeds.com/v1.1/pull/nhl/2016-2017-regular/player_gamelogs.json?player=jamie-benn&date=until-20161022
```
seems to respond with correct results.

am i missing something small here? after reading the documentation i saw there is no explicit example of a date-range between two specified dates where both specified dates are in YYYYMMDD format. is that not possible?

**Comment by bradbarkhouse** [comment]
Looks like a bug, thanks for finding that @dweitz43 !  We'll get it sorted soon.

**Comment by bradbarkhouse** [comment]
Fixed!
