### ISSUE TITLE
[NFL] Stadiums with the wrong name

### ISSUE THREAD

**Issue by friasricardo** [bradbarkhouse/mysportsfeeds-api#49]
Some stadiums have the wrong name:

Bills - New Era Field
Dolphins - Hard Rock Stadium
Vikings - U.S. Bank Stadium
Broncos - Sports Authority Field at Mile High
Saints - Mercedes-Benz Superdome
Raiders - Oakland Coliseum
Chargers - StubHub Center
Falcons - Mercedes-Benz Stadium

Games outside of USA:
Ravens @ Jaguars - 2017-09-24 - Wembley Stadium (London)
Saints @ Dolphins - 2017-10-01 - Wembley Stadium (London)
Cardinals @ Rams - 2017-10-22 - Twickenham Stadium (London)
Vikings @ Browns - 2017-10-29 - Twickenham Stadium (London)
Patriots @ Raiders - 2017-11-19 - Estadio Azteca (Mexico)

**Comment by bradbarkhouse** [comment]
We're guilty of not focusing enough on the venues for the games (across leagues, not just NFL).  As such, we'll need to get these corrected, thanks @ricardofrias!

**Comment by bradbarkhouse** [comment]
Okay, these should finally all be sorted!  We're now able to track teams and venues over time as part of naming changes or relocations.
