### ISSUE TITLE
Add numeric game id to Game Boxscores fields

### ISSUE THREAD

**Issue by zamorarr** [bradbarkhouse/mysportsfeeds-api#53]
Any reason why the *Game Boxscores* don't include the numeric game id as one of the returned fields? My use case is that I want to join the *Daily DFS* data to these box scores. The DFS feeds have a numeric game id (ex. 37733) included, but the box scores do not. I know that I can figure out a different form of the game id using the data, away team, and home team (ex. 20171019-STL-COL) but it would be nice to be able to do this on the numeric id. Specifically because then I don't have to worry about accounting for double headers in baseball.

**Comment by bradbarkhouse** [comment]
@zamorarr I can tell you that there's certainly no _good_ reason for this.  It's one of a number of inconsistencies that we've identified and are planning on correcting fully in v2.0.  Feeds will be completely refactored, and in fact in many cases it'll mean making fewer requests to get more of what you need.

**Comment by zamorarr** [comment]
@bradbarkhouse that's fair. Looking forward to v2.0!

**Comment by bradbarkhouse** [comment]
Done! (as part of v2.0)
