### ISSUE TITLE
OTW is broken

### ISSUE THREAD

**Issue by andyczerwonka** [bradbarkhouse/mysportsfeeds-api#54]
There is no way, with the current API, to track regulation wins. During that investigation, I noticed that the OTW stat is broken as it gives zero for OTW in all cases. If the API were to give all three, Total Wins, OTW and SOW, then we could easily calculate regulation wins: Total Wins - OTW - SOW = Regulation Wins

![image](https://user-images.githubusercontent.com/138898/34055126-15ad0078-e18b-11e7-9522-2cba865a4844.png)

**Comment by bradbarkhouse** [comment]
Finally!  This is now resolved along with the other hockey upgrades.
