### ISSUE TITLE
getting playoff scores from api is broken

### ISSUE THREAD

**Issue by jason1813** [bradbarkhouse/mysportsfeeds-api#55]
Nothing shows up when you try to get playoff scores for the nfl or daily schedule. This can be seen by going to this link:
https://api.mysportsfeeds.com/v1.1/pull/nfl/2017-2018-playoff/daily_game_schedule.json?fordate=20180106

Games should show up but you get nothing.

**Comment by bradbarkhouse** [comment]
They're there, you just need to specify the corrwct season identifier for the playoffs, or use the keyword "current" as specified in the API Docs.

 https://api.mysportsfeeds.com/v1.1/pull/nfl/2018-playoff/daily_game_schedule.json?fordate=20180106

https://api.mysportsfeeds.com/v1.1/pull/nfl/current/daily_game_schedule.json?fordate=20180106

**Comment by jason1813** [comment]
Thank you!!!!!!!!!

**Comment by jason1813** [comment]
Also question. Is there a way to pull the current dates games? Instead of having to specify the current date: 20180106

**Comment by bradbarkhouse** [comment]
Not at the moment no, but that's an interesting idea.  V2.0 will be released later this year ...
