### ISSUE TITLE
Wrong data structure for stats - some entries contain an array of identical objects instead of an object.

### ISSUE THREAD

**Issue by wujekbogdan** [bradbarkhouse/mysportsfeeds-api#58]
Here's an example.

`Sacks` and `TackleTotal` and `GamesPlayer` entries look fine. They contain objects. But all other entries contain arrays of objects identical objects.

<img width="650" alt="strange-stats" src="https://user-images.githubusercontent.com/533954/35615025-e0c7965e-0668-11e8-9df4-6017ab667ee3.png">

**Comment by bradbarkhouse** [comment]
Do you have the URL you used for this @wujekbogdan ?  Definitely doesn't look right, but can't reproduce atm.
