### ISSUE TITLE
Confusing data structure for NHL stats - another stats object nested under stats

### ISSUE THREAD

**Issue by wujekbogdan** [bradbarkhouse/mysportsfeeds-api#59]
According to the documentation, this is the proper structure for stats for the team standings endpoint:

```
https://api.mysportsfeeds.com/v1.1/pull/nhl/2017-2018-regular/division_team_standings.json?teamstats=W,L,GF,GA,Pts
```

``` json
"stats": {
  "GamesPlayed": {
    "@abbreviation": "GP",
      "#text": "1"
  },
  "Wins": {
    "@abbreviation": "W",
      "#text": "0"
  },
  "Losses": {
    "@abbreviation": "L",
      "#text": "1"
  }
}
// ... more stats
```

But in reality, the structure is messed up. The `GamesPlayed` entry is under the `stats` entry, but other items are listed under another, nested `stats` property. See the screenshot below:

<img width="468" alt="stats-structure" src="https://user-images.githubusercontent.com/533954/35615223-680eda96-0669-11e8-9a63-3110b088a965.png">

---
PS
I'm not sure if this problem applies only to the `division_team_standings.json` endpoint. I've already applied a workaround (a normalizer) in my code so I'm no longer seeing problems caused by this issue.

**Comment by bradbarkhouse** [comment]
Thanks @wujekbogdan , this is a great example of why the data structures will be redesigned for v2.0.  The "GamesPlayed" should indeed have been grouped under the other "stats" object.  We'll need to modify the current API Docs samples to reflect that, but for stability purposes, no structural changes can be made for v1.x right now.

**Comment by bradbarkhouse** [comment]
Done!
