### ISSUE TITLE
[Website usability issue] Add #hash based routing

### ISSUE THREAD

**Issue by wujekbogdan** [bradbarkhouse/mysportsfeeds-api#61]
It's a bit annoying that feeds pages share the same URL (`https://www.mysportsfeeds.com/data-feeds/api-docs/#`). Because of that we can't bookmark these pages or send a link to a specific documentation page. Documentation pages are rendered with JS I guess, so it should be quite easy to add simple hash-based routing.

**Comment by bradbarkhouse** [comment]
Actually, the entire API Docs is going to be replaced by a Swagger-based solution.  Because of all API the versions and the static sample responses included in the page, the initial load of the overall page is becoming increasingly slow and clunky.
