### ISSUE TITLE
NFL Play By Play for 20151108-NYG-TB - First two plays reversed

### ISSUE THREAD

**Issue by BobBrennan** [bradbarkhouse/mysportsfeeds-api#66]
This game starts off with a passing play (Intercepted) followed by the opening Kickoff

<gam:gameplaybyplay xmlns:gam="http://leaguemanager.beacontender.com/plugin/feed/sport/usftbl/gameplaybyplay">
<gam:lastUpdatedOn>2018-02-18 12:55:53 PM</gam:lastUpdatedOn>
<gam:game>
<gam:date>2015-11-08</gam:date>
<gam:time>8:30PM</gam:time>
<gam:awayTeam>
<gam:ID>53</gam:ID>
<gam:City>New York</gam:City>
<gam:Name>Giants</gam:Name>
<gam:Abbreviation>NYG</gam:Abbreviation>
</gam:awayTeam>
<gam:homeTeam>
<gam:ID>71</gam:ID>
<gam:City>Tampa Bay</gam:City>
<gam:Name>Buccaneers</gam:Name>
<gam:Abbreviation>TB</gam:Abbreviation>
</gam:homeTeam>
<gam:location>Raymond James Stadium</gam:location>
</gam:game>
<gam:plays>
<gam:play>
<gam:currentDown>1</gam:currentDown>
<gam:yardsRemaining>10</gam:yardsRemaining>
<gam:lineOfScrimmage>
<gam:team>NYG</gam:team>
<gam:yardLine>20</gam:yardLine>
</gam:lineOfScrimmage>
<gam:quarter>1</gam:quarter>
<gam:time>0:00</gam:time>
<gam:description>
(15:00) (Shotgun) E.Manning pass short right intended for O.Beckham Jr. INTERCEPTED by S.Moore at NYG 31. S.Moore pushed ob at NYG 13 for 18 yards (D.Harris).
</gam:description>
<gam:passingPlay>
<gam:teamAbbreviation>NYG</gam:teamAbbreviation>
<gam:passingPlayer>
<gam:ID>7734</gam:ID>
<gam:LastName>Manning</gam:LastName>
<gam:FirstName>Eli</gam:FirstName>
<gam:JerseyNumber>10</gam:JerseyNumber>
<gam:Position>QB</gam:Position>
</gam:passingPlayer>
<gam:receivingPlayer>
<gam:ID>7746</gam:ID>
<gam:LastName>Beckham</gam:LastName>
<gam:FirstName>Odell</gam:FirstName>
<gam:JerseyNumber>13</gam:JerseyNumber>
<gam:Position>WR</gam:Position>
</gam:receivingPlayer>
<gam:interceptingPlayer>
<gam:ID>8623</gam:ID>
<gam:LastName>Moore</gam:LastName>
<gam:FirstName>Sterling</gam:FirstName>
<gam:JerseyNumber>26</gam:JerseyNumber>
<gam:Position>DB</gam:Position>
</gam:interceptingPlayer>
<gam:interceptedAtPosition>
<gam:team>NYG</gam:team>
<gam:yardLine>31</gam:yardLine>
</gam:interceptedAtPosition>
<gam:soloTacklingPlayer>
<gam:ID>7752</gam:ID>
<gam:LastName>Harris</gam:LastName>
<gam:FirstName>Dwayne</gam:FirstName>
<gam:JerseyNumber>17</gam:JerseyNumber>
<gam:Position>WR</gam:Position>
</gam:soloTacklingPlayer>
<gam:stoppedAtPosition>
<gam:team>NYG</gam:team>
<gam:yardLine>13</gam:yardLine>
</gam:stoppedAtPosition>
<gam:isCompleted>false</gam:isCompleted>
<gam:isOutOfBounds>false</gam:isOutOfBounds>
<gam:isTackled>false</gam:isTackled>
<gam:isEndedWithTouchdown>false</gam:isEndedWithTouchdown>
<gam:isTwoPointConversion>false</gam:isTwoPointConversion>
<gam:isFirstDownPenalty>false</gam:isFirstDownPenalty>
<gam:isNoPlay>false</gam:isNoPlay>
<gam:yardsPassed>11</gam:yardsPassed>
<gam:yardsRushed>-18</gam:yardsRushed>
<gam:yardsIntercepted>18</gam:yardsIntercepted>
<gam:totalYardsGained>-7</gam:totalYardsGained>
</gam:passingPlay>
</gam:play>
<gam:play>
<gam:currentDown>0</gam:currentDown>
<gam:yardsRemaining>0</gam:yardsRemaining>
<gam:lineOfScrimmage>
<gam:team>TB</gam:team>
<gam:yardLine>35</gam:yardLine>
</gam:lineOfScrimmage>
<gam:quarter>1</gam:quarter>
<gam:time>0:00</gam:time>
<gam:description>
C.Barth kicks 65 yards from TB 35 to end zone, Touchback.
</gam:description>
<gam:kickingPlay>
<gam:kickingTeamAbbreviation>TB</gam:kickingTeamAbbreviation>
<gam:kickingPlayer>
<gam:ID>6818</gam:ID>
<gam:LastName>Barth</gam:LastName>
<gam:FirstName>Connor</gam:FirstName>
<gam:JerseyNumber>10</gam:JerseyNumber>
<gam:Position>K</gam:Position>
</gam:kickingPlayer>
<gam:kickedFromPosition>
<gam:team>TB</gam:team>
<gam:yardLine>35</gam:yardLine>
</gam:kickedFromPosition>
<gam:stoppedAtPosition>
<gam:team>NYG</gam:team>
<gam:yardLine>0</gam:yardLine>
</gam:stoppedAtPosition>
<gam:isKickoff>true</gam:isKickoff>
<gam:isPunt>false</gam:isPunt>
<gam:isBlocked>false</gam:isBlocked>
<gam:isTouchback>true</gam:isTouchback>
<gam:isSafety>false</gam:isSafety>
<gam:isOutOfBounds>false</gam:isOutOfBounds>
<gam:isTouchdown>false</gam:isTouchdown>
<gam:isFairCatch>false</gam:isFairCatch>
<gam:isLanded>false</gam:isLanded>
<gam:isOnside>false</gam:isOnside>
<gam:isFirstDownPenalty>false</gam:isFirstDownPenalty>
<gam:isNoPlay>false</gam:isNoPlay>
<gam:yardsKicked>65</gam:yardsKicked>
<gam:yardsReturned>0</gam:yardsReturned>
</gam:kickingPlay>
</gam:play>

**Comment by bradbarkhouse** [comment]
Fixed!
