### ISSUE TITLE
current_season does not returns null for first day of season

### ISSUE THREAD

**Issue by thegreatco** [bradbarkhouse/mysportsfeeds-api#68]
The first day of the 2017-2018 basketball season is October 17, 2017. However when that date is fed to the `current_season` endpoint, it returns null. 

Running the request with postman `https://api.mysportsfeeds.com/v1.2/pull/nba/current_season.json?fordate=20171017` yields

    {"currentseason":{"lastUpdatedOn":"2018-03-04 4:08:48 PM","season":[null]}}

Giving it the following day (`20171018`) works just fine.

**Comment by bradbarkhouse** [comment]
Thx @thegreatco !  Looks like an easy fix, I'll followup here when a fix is made.

**Comment by bradbarkhouse** [comment]
Fixed!
