### ISSUE TITLE
Inconsistent field naming

### ISSUE THREAD

**Issue by thegreatco** [bradbarkhouse/mysportsfeeds-api#69]
Calling the `full_game_schedule` endpoint yields some inconsistent field names. For example:

`fullgameschedule` (the root element) is not camel cased, while most of the API is. Suggested name `fullGameSchedule`

`fullgameschedule.gameentry` implies it is singular, but it is an array. For clarity, suggested name `fullGameSchedule.gameEntries`

Inside an element of `fullgameschedule.gameentry` (I'll call it `gameEntry` for clarity) there are 2 fields, `homeTeam` and `awayTeam`, which have 4 fields:

- `ID`
- `City`
- `Name`
- `Abbreviation`

Since most of the API is lowerCamelCase (common in JSON), I suggest renaming to `id`, `city`, `name`, `abbreviation` for consistency.

As I haven't reviewed the full API, these issues might exist elsewhere, so a full review might be prudent.

**Comment by bradbarkhouse** [comment]
Yep, those are just some of the inconsistencies of our initial v1.0 rollout of the API.  V2.0 will aim to resolve this and several other structural and syntax annoyances.

We'll probably go with camelCase.  However, we're also toying with the idea of also including the under_score format as an additional configurable option.

**Comment by acoll** [comment]
Hey @bradbarkhouse I'm running into some of these issues also. The data coverage is fantastic but some of these inconsistencies make stuff pretty messy to work with. If you are ever looking for devs to contribute towards some of this stuff let me know. Something like [swagger](https://swagger.io/) or GraphQL would be pretty cool to get a stricter definition of responses.

**Comment by bradbarkhouse** [comment]
Thanks for the feedback @acoll !

Agreed on the inconsistencies.  As mentioned above, these are symptoms of the initial 1.x version.  v2.0 will resolve these.  As for Swagger or API doc tooling, we actually prefer to roll our own.

**Comment by acoll** [comment]
Sounds awesome. Looking forward to it. Is there any rough timeline on 2.0? Days, weeks, months, years...?

Also if you are looking for beta / early testers let me know.

**Comment by bradbarkhouse** [comment]
It'll be a few months yet.  Still working on other priorities (salary, bios, etc).

**Comment by bradbarkhouse** [comment]
Done!
