### ISSUE TITLE
Include strength in Game Play-by-Play request

### ISSUE THREAD

**Issue by danpanaite** [bradbarkhouse/mysportsfeeds-api#70]
Currently, it's hard to determine whether a play has occurred at even strength or during a powerplay. Adding a "strength" property to each play would provide an easier approach to calculating advanced hockey statistics like Corsi/Fenwick

**Comment by bradbarkhouse** [comment]
I assume you mean across all plays, not just goals.  Great suggestion!

**Comment by danpanaite** [comment]
Yea all plays would be great!

**Comment by bradbarkhouse** [comment]
Done!
