### ISSUE TITLE
Add Time Zone To Dates/Times in API

### ISSUE THREAD

**Issue by thegreatco** [bradbarkhouse/mysportsfeeds-api#71]
Date/Times in the API are ambiguous as they don't include any timezone information. I would suggest switching over to [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) with timezone. For example
```
lastUpdatedOn": "2018-03-24 10:50:25 AM",
```
would become
```
lastUpdatedOn": "2018-03-24T10:50:25-0400",
```
For games
```
"date": "2017-10-17",
"time": "8:00PM",
```
would become:
```
"date":"2017-10-17T20:00:00-0400"
```
This has the added benefit of allowing game times to be specified clearly in either in UTC or the local time of the game while allowing clients to easily convert to an appropriate display time.

**Comment by bradbarkhouse** [comment]
Thanks @thegreatco!  This is a popular request, and will be included as part of the v2.0 improvements.

**Comment by thegreatco** [comment]
👍

**Comment by bradbarkhouse** [comment]
Done!
