### ISSUE TITLE
Respect If-Modified-Since header

### ISSUE THREAD

**Issue by thegreatco** [bradbarkhouse/mysportsfeeds-api#72]
According to the API docs, adding `force=false` to a request will return a `304` if the data hasn't been modified since the last request for it. However this does not take into account multiple applications accessing the API. For a quick example, if you are running a QA and a Production application instance, relying on `force=false` prevents one of the applications from receiving the updates as the MySportsFeed servers don't see them as distinct entities. If the server respects the `If-Modified-Since` header, it allows the application instances to throttle themselves.

**Comment by bradbarkhouse** [comment]
The header's a good idea @thegreatco .  Currently in v1.x to get around this, separate accounts would be needed, and we have in fact done this for several subscribers.

API v2.0 will introduce API "keys" which will work in a similar manner, but won't require the creation of several accounts.

**Comment by bradbarkhouse** [comment]
Along with the new API Keys, this shouldn't be as high a concern.

**Comment by thegreatco** [comment]
👍
