### ISSUE TITLE
Stats feeds returning incorrect results (when using similar filters within seconds of each other)

### ISSUE THREAD

**Issue by caroig** [bradbarkhouse/mysportsfeeds-api#73]
We have two stats widgets on a single page, both request the same feed with different parameters.

**Feed A**
https://api.mysportsfeeds.com/v1.1/pull/nfl/2017-regular/cumulative_player_stats.json/?team=CLE&playerstats=Total,Sacks,INT

**Feed B**
https://api.mysportsfeeds.com/v1.1/pull/nfl/2017-regular/cumulative_player_stats.json/?team=CLE&playerstats=Yds

With caching off, occasionally one or the other feed will return results that we don't expect.  On inspection, feed A is returning results for feed B, and vice versa.  It doesn't happen every time, but it does happen frequently.

The problem can be reproduced in the browser, entering the 2 feeds in two tabs, refreshing and switching between them.  I've attached a video that shows this happening.  

[api-bug-720.zip](https://github.com/MySportsFeeds/mysportsfeeds-api/files/1863832/api-bug-720.zip)

**Comment by bradbarkhouse** [comment]
Thanks a lot for this @caroig !  What I suspect is happening here is a race condition having to do with our internal caching algorithm.  Essentially, we try to assess whether your request is just a repeat of your last request for the same feed, and if so, just serve you the last response.  This saves us countless bandwidth and CPU resources.  When the requests come in rapid succession, that seems to be going awry in this case.

We'll need to tighten that up, but in the meantime you can avoid it by pacing your requests to the same feed a few seconds apart.

**Comment by bradbarkhouse** [comment]
I'm unable to reproduce this now @caroig since the v2.0 release and corresponding changes.  Can you confirm?
