### ISSUE TITLE
Wrong birthday on NBA active player

### ISSUE THREAD

**Issue by angeagu** [bradbarkhouse/mysportsfeeds-api#74]
Playing around a little bit with NBA feed for 2016-17 season, I found out that player "ID":"14398","LastName":"Jackson","FirstName":"Aaron","Position":"SG","BirthDate":"2018-04-11"
has wrong BirthDate field.

**Comment by bradbarkhouse** [comment]
@angeagu okay thanks for that!  But all subscribers can actually suggest player changes directly on the site.  Just search for the player, and click the green "Suggest Changes" button.  We'll review and accept/reject pretty quickly.

**Comment by angeagu** [comment]
@bradbarkhouse ok, thanks for info! Will do it next time ;)
