### ISSUE TITLE
The API sometimes returns the data for multiple players instead of the specified one

### ISSUE THREAD

**Issue by wujekbogdan** [bradbarkhouse/mysportsfeeds-api#76]
I had this problem with the following endpoint:

```
https://api.mysportsfeeds.com/v1.1/pull/mlb/2017-regular/cumulative_player_stats.json/?player=edwin-encarnacion-11029&team=CLE
```

Sometimes the API returns results for multiple players like the `player` parameter was ignored. It's very hard to reproduce because it happens occasionally.

It's not a player-specific issue. It happens with different teams and different players.

---
It might be related to: https://github.com/MySportsFeeds/mysportsfeeds-api/issues/73

**Comment by bradbarkhouse** [comment]
I'm unable to reproduce this @wujekbogdan , since the v2.0 release.  Can you confirm?
