### ISSUE TITLE
[API design change proposal] Use stats properties instead of stats abbreviations for the playerstats parameter

### ISSUE THREAD

**Issue by wujekbogdan** [bradbarkhouse/mysportsfeeds-api#77]
I see that there's v2.0 on the way so it's a good chance to fix things :)

I found the `playerstats` parameter odd. I was surprised that if a single stat abbreviation is supplied then sometimes I get multiple stats in the response. Then I realized that it's not a bug because stats abbreviations are not unique.

This architecture makes the application architecture more complicated because responses are not reliable. After a response is received from the API, stats must be filtered by their properties in order to filter out stats that we don't need.

Consider the following request:

```
https://api.mysportsfeeds.com/v1.1/pull/nfl/2017-regular/cumulative_player_stats.json/?playerstats=Yds
```

It results in the following stats format:

``` json
// ...
"stats": {
  "GamesPlayed": {
    "@abbreviation": "G",
    "#text": "16"
  },
  "IntYds": {
    "@category": "Interceptions",
    "@abbreviation": "Yds",
    "#text": "0"
  },
  "KrYds": {
    "@category": "Kickoff Returns",
    "@abbreviation": "Yds",
    "#text": "0"
  },
  "PrYds": {
    "@category": "Punt Returns",
    "@abbreviation": "Yds",
    "#text": "0"
  }
}
```

It happens because the  `Yds` abbreviation stands for: `PrYds`, `KrYds`, `IntYds` (and a few more `*Yds` stats properties).

---

IMO, instead of stats abbreviations, the `playerstats` parameter should take stats properties that are unique.

**Comment by bradbarkhouse** [comment]
Thanks for the feedback @wujekbogdan !  It's for this very reason that you can also prefix each stat abbreviation with it's category.  So it would become:

https://api.mysportsfeeds.com/v1.1/pull/nfl/2017-regular/cumulative_player_stats.json?playerstats=Interceptions.Yds,Punt%20Returns.Yds,Kickoff%20Returns.Yds

This same parameter syntax will likely be carried forward with v2.0 as well.   Does that help?

**Comment by wujekbogdan** [comment]
@bradbarkhouse 

> you can also prefix each stat abbreviation with it's category.

Thanks, I didn't know about it. It would be good to add this information to docs.

> This same parameter syntax will likely be carried forward with v2.0 as well. Does that help?

To be honest, I would prefer to use stats properties (or other unique identifiers) instead of creating combined parameters :) It would make application's data models simpler.

**Comment by bradbarkhouse** [comment]
@wujekbogdan 
Oops, thought it was in the Docs already, we can get that amended.

We already have unique names for each stat, so it'd be trivial to overload the playerstats param to support those as well.  But in a lot of cases, for other sports, these can be a bit long (baseball), so it might be nice to have a choice.  We'll get that done for v2.0 as well!

**Comment by bradbarkhouse** [comment]
Done!
