### ISSUE TITLE
Weird results for NHL player stats: only one entry received in the response

### ISSUE THREAD

**Issue by wujekbogdan** [bradbarkhouse/mysportsfeeds-api#78]
Request URL: `https://api.mysportsfeeds.com/v1.1/pull/nhl/2017-2018-regular/cumulative_player_stats.json/`
playerstats: `GP,W,L,OTL,GAA,GA,Sv,Sv%,SO`

The result contains just one entry:

```
{
    "cumulativeplayerstats": {
        "lastUpdatedOn": "2018-04-16 11:12:29 AM",
        "playerstatsentry": [
            {
                "player": {
                    "ID": "4406",
                    "LastName": "Okposo",
                    "FirstName": "Kyle",
                    "JerseyNumber": "21",
                    "Position": "RW",
                    "Height": "6'0\"",
                    "Weight": "220",
                    "BirthDate": "1988-04-16",
                    "Age": "30",
                    "BirthCity": "St. Paul, MN",
                    "BirthCountry": "USA",
                    "IsRookie": "false"
                },
                "team": {
                    "ID": "15",
                    "City": "Buffalo",
                    "Name": "Sabres",
                    "Abbreviation": "BUF"
                },
                "stats": {
                    "GamesPlayed": {
                        "@abbreviation": "GP",
                        "#text": "76"
                    },
                    "stats": {
                        "Goals": {
                            "@abbreviation": "G",
                            "#text": "15"
                        },
                        "Assists": {
                            "@abbreviation": "A",
                            "#text": "29"
                        },
                        "Points": {
                            "@abbreviation": "Pts",
                            "#text": "44"
                        },
                        "HatTricks": {
                            "@abbreviation": "Hat",
                            "#text": "0"
                        },
                        "PlusMinus": {
                            "@abbreviation": "+/-",
                            "#text": "-34"
                        },
                        "Shots": {
                            "@abbreviation": "Sh",
                            "#text": "161"
                        },
                        "BlockedShots": {
                            "@abbreviation": "BS",
                            "#text": "33"
                        },
                        "ShotPercentage": {
                            "@abbreviation": "Sh%",
                            "#text": "9.3"
                        },
                        "Penalties": {
                            "@abbreviation": "Pn",
                            "#text": "20"
                        },
                        "PenaltyMinutes": {
                            "@abbreviation": "PIM",
                            "#text": "40"
                        },
                        "PowerplayGoals": {
                            "@abbreviation": "PPG",
                            "#text": "6"
                        },
                        "PowerplayAssists": {
                            "@abbreviation": "PPA",
                            "#text": "15"
                        },
                        "PowerplayPoints": {
                            "@abbreviation": "PPPts",
                            "#text": "21"
                        },
                        "ShorthandedGoals": {
                            "@abbreviation": "SHG",
                            "#text": "0"
                        },
                        "ShorthandedAssists": {
                            "@abbreviation": "SHA",
                            "#text": "0"
                        },
                        "ShorthandedPoints": {
                            "@abbreviation": "SHPts",
                            "#text": "0"
                        },
                        "GameWinningGoals": {
                            "@abbreviation": "GWG",
                            "#text": "2"
                        },
                        "GameTyingGoals": {
                            "@abbreviation": "GTG",
                            "#text": "0"
                        },
                        "Hits": {
                            "@abbreviation": "Ht",
                            "#text": "70"
                        },
                        "Faceoffs": {
                            "@abbreviation": "FO",
                            "#text": "50"
                        },
                        "FaceoffWins": {
                            "@abbreviation": "F/O W",
                            "#text": "23"
                        },
                        "FaceoffLosses": {
                            "@abbreviation": "F/O L",
                            "#text": "27"
                        },
                        "FaceoffPercent": {
                            "@abbreviation": "F/O %",
                            "#text": "046.0"
                        }
                    }
                }
            }
        ]
    }
}
```

But If I ommit the `Sv%` parameter then the results are correct - I see much more entries.

I thought it migt be en encoding issue of the `%` sign but I performed this test with Postman and with Guzzle - in both cases the reults are the same. 

---
PS
I'm not sure is it related but sometimes I receive an error 400 instead of 200. It't not consistent, but usually happens at the first try, all supsequent tries return code 200.

**Comment by bradbarkhouse** [comment]
@wujekbogdan this definitely looks like a syntax issue related to the player stats encoding.  Your request URL doesn't seem to indicate how you formed the playerstats parameter.

Essentially, all stat abbreviations need to be URL-encoded.  The GP stat is implicit, it can be removed from the list.  Further, since you seem to want only goalie stats, you can further filter by position "G".  The request URL should then look like:

https://api.mysportsfeeds.com/v1.1/pull/nhl/2017-2018-regular/cumulative_player_stats.json?position=G&playerstats=W,L,OTL,GAA,GA,Sv,Sv%25,SO

**Comment by wujekbogdan** [comment]
@bradbarkhouse

> this definitely looks like a syntax issue related to the player stats encoding. Your request URL doesn't seem to indicate how you formed the playerstats parameter.

I make requests via [Guzzle](http://docs.guzzlephp.org/en/stable/) (a PHP HTTP client). I was also testing the same request using [Postman](https://www.getpostman.com/) (a standalone HTTP Client). As far I know, both these tools take care of proper parameters encoding (correct me if I'm wrong).

So, in this case, the Guzzle GET call would look as follows:

``` php
<?php
use \GuzzleHttp\Client;

$client = new Client([
    'base_uri' => 'https://api.mysportsfeeds.com/v1.1/pull/',
    'auth' => [
        'myUserName',
        'myPassword'
    ]
]);

$client->get('/nhl/2017-2018-regular/cumulative_player_stats.json/', [
    'query' => [
        'playerstats' => 'GP,W,L,OTL,GAA,GA,Sv,Sv%,SO'
    ]
]);
```

But even if the weird result I received was caused by wrong encoding then I would expect an error 400 to be returned by the API not error 200 with just one results.

---

Additionally, other requests that contain `%` character return proper results. For example when I call `nfl/2017-regular/cumulative_player_stats.json/` endpoint with the following set of playerststs: `Comp,Att,Pct,Yds,Yards/Att,TD,Int,Sacks,TD%,Int%,QBRating` then everything is fine.

So IMO this it definitely looks like a bug.

> Further, since you seem to want only goalie stats, you can further filter by position "G". The request URL should then look like: https://api.mysportsfeeds.com/v1.1/pull/nhl/2017-2018-regular/cumulative_player_stats.json?position=G&playerstats=W,L,OTL,GAA,GA,Sv,Sv%25,SO

True, but this is just an example :)

**Comment by bradbarkhouse** [comment]
@wujekbogdan aha, yes I think this IS indeed a bug.  You're correct in saying that an unrecognized stat abbreviation should result in a 400.  And it does - the FIRST time you request it.  Then on subsequent requests, I think you're getting a 200 with your most previous successful request's content.  So it looks like a bug in the caching algorithm, which should be relatively easy to fix.

So in your case, I think the NHL request failed with a 400 b/c of the "GP" stat you included - which is treated as an implicit stat, so it couldn't resolve it.  And that's also why your NFL request above succeeded the first time.

So we'll definitely put a patch in for this, thanks!

**Comment by bradbarkhouse** [comment]
Are you still seeing this behaviour @wujekbogdan ?
