### ISSUE TITLE
full_game_schedule endpoint returns 400 responses

### ISSUE THREAD

**Issue by wujekbogdan** [bradbarkhouse/mysportsfeeds-api#81]
It started to happen today.  The following request returns 400. It's not team dependent, I tried with various teams.

```
https://api.mysportsfeeds.com/v1.1/pull/nhl/current/full_game_schedule.json/?team=CAR
```

**Comment by bradbarkhouse** [comment]
Curious, might have been b/c we had yet to add the remaining 7 games for the Stanley Cup Finals after last night's Eastern Conference game 7.

Works when I specify a playoff team:

https://api.mysportsfeeds.com/v1.1/pull/nhl/current/full_game_schedule.json/?team=wsh
