### ISSUE TITLE
Error in API Request for NodeJS

### ISSUE THREAD

**Issue by SamNadjari** [bradbarkhouse/mysportsfeeds-api#86]
I followed the code given on the GitHub page for node: 
![image](https://user-images.githubusercontent.com/31825178/42414698-b5f6c780-8208-11e8-8ca1-6875bfe1044a.png)
But when I run the application I get this error: 
![image](https://user-images.githubusercontent.com/31825178/42414699-d15436fc-8208-11e8-971d-b97cecea2512.png)

Any help resolving this would be greatly appreciated.

**Comment by bradbarkhouse** [comment]
Oops, you included an extra "s" in your season identifier.  Try:

https://api.mysportsfeeds.com/v1.2/pull/mlb/2016-playoff/full_game_schedule.json
