### ISSUE TITLE
NHL 2018-19 standings .csv

### ISSUE THREAD

**Issue by pi3r8** [bradbarkhouse/mysportsfeeds-api#96]
when trying to pull the NHL standings for this season as a .csv I receive a 400 error after the authentication prompt.
Sample URL: https://api.mysportsfeeds.com/v2.0/pull/nhl/2018-2019-regular/standings.csv
![image](https://user-images.githubusercontent.com/44070299/46827257-15d40000-cd90-11e8-9221-793d37394bac.png)

**Comment by bradbarkhouse** [comment]
It's because The v2.0 standings feed doesn't have a CSV format.  You'll need to choose ether JSON or XML.
