### ISSUE TITLE
Cannot get the api work on php wrapper

### ISSUE THREAD

**Issue by vahharris** [bradbarkhouse/mysportsfeeds-api#97]
Fatal error: Cannot redeclare MySportsFeeds\BaseApi::__determineUrl() in /Applications/MAMP/htdocs/apis/vendor/mysportsfeeds/mysportsfeeds-php/src/BaseApi.php on line 64

![image](https://user-images.githubusercontent.com/14223214/55991966-6e218700-5c79-11e9-9b33-f098055da935.png)

**Comment by bradbarkhouse** [comment]
This is related to the PHP wrapper, misplaced.
